spring.application.name=turnos
spring.datasource.url=jdbc:postgresql://localhost:5433/turnos_consultorio
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=10000
spring.sql.init.mode=never
server.port=8085

mp.access.token=APP_USR-5439891317709627-041017-93b6f8aaad5ef225037602b36366a048-3292338795
jwt.secret=zyxwvutsrqponmlkjihgfedcba987654321
jwt.expiration.ms=3600000

frontend.url=http://localhost:5173

# URL del Backend (donde corre tu Spring Boot)
backend.url=http://localhost:8085